/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/volt/Button.vue')['default']
    Card: typeof import('./src/volt/Card.vue')['default']
    ContrastButton: typeof import('./src/volt/ContrastButton.vue')['default']
    DangerButton: typeof import('./src/volt/DangerButton.vue')['default']
    DataTable: typeof import('./src/volt/DataTable.vue')['default']
    Dialog: typeof import('./src/volt/Dialog.vue')['default']
    Divider: typeof import('./src/volt/Divider.vue')['default']
    InputText: typeof import('./src/volt/InputText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryButton: typeof import('./src/volt/SecondaryButton.vue')['default']
    Select: typeof import('./src/volt/Select.vue')['default']
  }
}
