/**
 * Hand-curated allow-list of every Iconify icon name (canonical colon form) this app is allowed
 * to bundle. wayfinder ticket 041 — this is the file a human edits when a new icon is needed;
 * `scripts/check-icons.mjs` fails the build if source references a name not listed here, and
 * `scripts/generate-icons.mjs` fails the build if a listed name isn't found in its collection.
 *
 * Generated by running `scripts/icons/extract-used.mjs` against `src/` and cross-checking a hand
 * trace of every `import { Icon } from '@iconify/vue'` call site (2026-09-01). Six names below
 * (`mdi:help-circle-outline` and five `solar:*` role icons) come from
 * `src/enums/modules/employee/EmployeeRole.enum.ts` — a leftover from the lending-app template
 * this repo started from (see `AGENTS.md`) with no importer anywhere in `src/`. They are kept on
 * the allow-list rather than the file being deleted, because deleting dead code is outside this
 * ticket's scope; the gate scans source text, not reachability, on purpose (see
 * `docs/wayfinder/tickets/041-iconify-fetches-every-icon-at-runtime.md`).
 */
export const ALLOWED_ICONS = [
  'bxs:image-add',
  'lets-icons:back-light',
  'lucide:copy',
  'lucide:ellipsis',
  'lucide:hard-drive-download',
  'material-icon-theme:pdf',
  'material-symbols:schedule-outline',
  'mdi:bell-outline',
  'mdi:check-circle',
  'mdi:chevron-double-left',
  'mdi:chevron-double-right',
  'mdi:chevron-down',
  'mdi:chevron-left',
  'mdi:chevron-right',
  'mdi:chevron-up',
  'mdi:close',
  'mdi:close-circle',
  'mdi:file',
  'mdi:help-circle-outline',
  'mdi:logout',
  'mdi:menu',
  'mdi:paperclip',
  'mdi:pencil',
  'mdi:plus',
  'mdi:refresh',
  'mdi:trash-can',
  'mdi:trash-can-outline',
  'mynaui:filter-solid',
  'ph:check-bold',
  'ph:x-bold',
  'qlementine-icons:menu-dots-16',
  'solar:alarm-turn-off-broken',
  'solar:bill-list-bold',
  'solar:inbox-line-outline',
  'solar:shield-star-bold',
  'solar:user-bold',
  'solar:user-check-bold',
  'solar:user-speak-bold',
  'system-uicons:search',
  'vscode-icons:file-type-excel',
  'vscode-icons:file-type-image',
  'vscode-icons:file-type-pdf2',
  'vscode-icons:file-type-text',
  'vscode-icons:file-type-word',
  'vscode-icons:file-type-zip'
]
