import type { IconifyIcon } from '@iconify/utils'
import { addCollection, addIcon } from '@iconify/vue/offline'
import bundledIcons from '@/assets/icons/bundled-icons.gen.json'

/**
 * wayfinder ticket 041 — registers this app's bundled icon data with `@iconify/vue/offline`
 * instead of the default `@iconify/vue` entry point. The offline entry exports only
 * `{ Icon, addCollection, addIcon }` — no `addAPIProvider`, no `_api`, no network code compiled
 * in at all — so once an icon is registered here, rendering it can never fall back to a runtime
 * fetch against `api.iconify.design`, which is exactly the standing "no third-party runtime
 * request" constraint this repo's `AGENTS.md` documents and this ticket found broken.
 *
 * `bundled-icons.gen.json` is generated by `scripts/generate-icons.mjs` from
 * `scripts/icons/allowlist.mjs` — see that script for how to add a new icon.
 *
 * Hyphen-alias registration: the offline `Icon` component looks icons up by an exact string key
 * (`storage[props.icon]`, no normalization) but several call sites in this repo pass the hyphen
 * form (`mdi-close`, `lucide-copy`, …) instead of the canonical colon form (`mdi:close`,
 * `lucide:copy`). Rather than touch every call site, every icon is registered twice: once under
 * its colon form via `addCollection`, once under `<prefix>-<name>` via a direct `addIcon` call.
 */
interface IBundledIconGroup {
  prefix: string
  icons: Record<string, IconifyIcon>
}

const bundledIconGroups = bundledIcons as unknown as IBundledIconGroup[]

export const REGISTERED_ICON_NAMES: Set<string> = new Set()

let registered = false

export function registerIcons (): void {
  if (registered) return
  registered = true

  for (const group of bundledIconGroups) {
    addCollection(group)

    for (const name of Object.keys(group.icons)) {
      const colonForm = `${group.prefix}:${name}`
      const hyphenForm = `${group.prefix}-${name}`
      addIcon(hyphenForm, group.icons[name])
      REGISTERED_ICON_NAMES.add(colonForm)
      REGISTERED_ICON_NAMES.add(hyphenForm)
    }
  }
}

// Side-effect registration on import, so any file that imports `AppIcon.vue` — including a test
// that mounts it directly, without going through `main.ts` — gets a populated icon store without
// needing its own setup step.
registerIcons()
